//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFEE_SHOP_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietcongthuc
    {
        public int id_chitietcongthuc { get; set; }
        public Nullable<int> id_thucuong { get; set; }
        public double dinhluong { get; set; }
        public Nullable<int> idkhonguyenlieu { get; set; }
    
        public virtual thucuong thucuong { get; set; }
        public virtual khonguyenlieu khonguyenlieu { get; set; }
    }
}
