//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFEE_SHOP_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietnguyenlieudadung
    {
        public int idchitietnguyenlieudadung { get; set; }
        public Nullable<int> idnguyenlieudadung { get; set; }
        public Nullable<int> idkhonguyenlieu { get; set; }
        public Nullable<double> dinhluong { get; set; }
    
        public virtual khonguyenlieu khonguyenlieu { get; set; }
        public virtual nguyenlieudadung nguyenlieudadung { get; set; }
    }
}
