//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFEE_SHOP_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class khonguyenlieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khonguyenlieu()
        {
            this.chitietcongthucs = new HashSet<chitietcongthuc>();
            this.chitietnguyenlieudadungs = new HashSet<chitietnguyenlieudadung>();
            this.chitietnhapkhoes = new HashSet<chitietnhapkho>();
        }
    
        public int idkhonguyenlieu { get; set; }
        public string tennguyenlieu { get; set; }
        public string tendonvi_dinh_luong { get; set; }
        public Nullable<double> dinhluong { get; set; }
        public Nullable<bool> xoa_flag { get; set; }
        public Nullable<double> dinh_luong_toi_da { get; set; }
        public Nullable<double> dinh_luong_toi_thieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietcongthuc> chitietcongthucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietnguyenlieudadung> chitietnguyenlieudadungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietnhapkho> chitietnhapkhoes { get; set; }
    }
}
