//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFEE_SHOP_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhapkho
    {
        public int idnhapkho { get; set; }
        public string tendonvi_so_luong { get; set; }
        public int soluong { get; set; }
        public double dinhluong { get; set; }
        public System.DateTime ngaynhap { get; set; }
        public int idkhonguyenlieu { get; set; }
        public decimal dongia { get; set; }
        public int id_nhanvien { get; set; }
    
        public virtual khonguyenlieu khonguyenlieu { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
