//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFEE_SHOP_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class thucuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thucuong()
        {
            this.chitietcongthucs = new HashSet<chitietcongthuc>();
            this.chitiethoadons = new HashSet<chitiethoadon>();
        }
    
        public int id_thucuong { get; set; }
        public string tenthucuong { get; set; }
        public Nullable<decimal> giaban { get; set; }
        public Nullable<int> id_nhomthucuong { get; set; }
        public Nullable<bool> xoa_flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietcongthuc> chitietcongthucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
        public virtual nhomthucuong nhomthucuong { get; set; }
    }
}
